version: '3'
services:
    vue:
        build: .
        container_name: vue
        ports:
            - '8080:8080'
        stdin_open: true
        tty: true
        volumes:
            - ./app:/app
        working_dir: /app/portfolio
